<a href="https://colab.research.google.com/github/MariaNatiele/Redes_Neurais/blob/main/2_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

📚 Fontes
</br>
[Keras](https://keras.io/api/models/model_training_apis/)
</br>
[Sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

In [306]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split

In [307]:
dados = pd.read_csv('Credit2.csv', sep=';')

In [308]:
dados.shape

(1000, 11)

In [309]:
dados.head(2)

ID checking_status                  credit_history  duration  \
0   1              <0  critical/other existing credit         6   
1   2        0<=X<200                   existing paid        48   

   credit_amount  installment_commitment  residence_since  age  \
0           1169                       4                4   67   
1           5951                       2                2   22   

   existing_credits  num_dependents class  
0                 2               1  good  
1                 1               1   bad

In [310]:
#Separação das variaves dependente(Y) independente (X)
x = dados.iloc[:,1:10].values
y = dados.iloc[:,10].values


In [311]:
#ignora a primera e a última, x se torna um array e não mais um dataframe
x

array([['<0', 'critical/other existing credit', 6, ..., 67, 2, 1],
       ['0<=X<200', 'existing paid', 48, ..., 22, 1, 1],
       ['no checking', 'critical/other existing credit', 12, ..., 49, 1,
        2],
       ...,
       ['no checking', 'existing paid', 12, ..., 38, 1, 1],
       ['<0', 'existing paid', 45, ..., 23, 1, 1],
       ['0<=X<200', 'critical/other existing credit', 45, ..., 27, 1, 1]],
      dtype=object)

Transformação das categorias 	checking_status	 e credit_history usando o LabelEncoder e o OneHotEncoder

In [312]:
#LabelEncoder coluna checking_status
#Atribui valores de 0 a 3
labelencoder = LabelEncoder()
x[:,0] = labelencoder.fit_transform(x[:,0])
x

array([[1, 'critical/other existing credit', 6, ..., 67, 2, 1],
       [0, 'existing paid', 48, ..., 22, 1, 1],
       [3, 'critical/other existing credit', 12, ..., 49, 1, 2],
       ...,
       [3, 'existing paid', 12, ..., 38, 1, 1],
       [1, 'existing paid', 45, ..., 23, 1, 1],
       [0, 'critical/other existing credit', 45, ..., 27, 1, 1]],
      dtype=object)

In [313]:
#one hot encoder coluna credit_history
#Deve adicionar 5 colunas, não temos mais valor categórico apenas numérico, coluna -> [1]
onehotencoder = make_column_transformer((OneHotEncoder(categories='auto', sparse_output=False), [1]), remainder='passthrough')

x = onehotencoder.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 67, 2, 1],
       [0.0, 0.0, 0.0, ..., 22, 1, 1],
       [0.0, 1.0, 0.0, ..., 49, 1, 2],
       ...,
       [0.0, 0.0, 0.0, ..., 38, 1, 1],
       [0.0, 0.0, 0.0, ..., 23, 1, 1],
       [0.0, 1.0, 0.0, ..., 27, 1, 1]], dtype=object)

In [314]:
#Excluindo uma das variaveis para evitar o dummy variable trop
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 67, 2, 1],
       [0.0, 0.0, 1.0, ..., 22, 1, 1],
       [1.0, 0.0, 0.0, ..., 49, 1, 2],
       ...,
       [0.0, 0.0, 1.0, ..., 38, 1, 1],
       [0.0, 0.0, 1.0, ..., 23, 1, 1],
       [1.0, 0.0, 0.0, ..., 27, 1, 1]], dtype=object)

In [315]:
#Label encoder com a classe, transfroma dados categóricos em numericos -> os 'good' em 0 e 1
labelencoderY= LabelEncoder()
y = labelencoderY.fit_transform(y)
y

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [316]:
#Separação treino e teste
x_treino, x_teste, y_treino , y_teste = train_test_split(x, y, test_size=0.2, random_state=0)
#Tramanho de cada array
print(len(x_treino),len(x_teste), len(y_treino), len(y_teste))

800 200 800 200


In [317]:
print(x_teste.shape, x_treino.shape)
print(y_teste.shape, y_treino.shape)

(200, 12) (800, 12)
(200,) (800,)


In [318]:
#Padronizar z-score, ultimo processo de transformção
sc = StandardScaler()
x_treino = sc.fit_transform(x_treino)
x_teste = sc.transform(x_teste)
x_teste

array([[-0.65270587, -0.30966177,  0.95357636, ..., -0.50870719,
        -0.71596668, -0.42214126],
       [-0.65270587, -0.30966177,  0.95357636, ..., -0.85315557,
        -0.71596668,  2.36887531],
       [-0.65270587, -0.30966177,  0.95357636, ...,  0.61075002,
        -0.71596668, -0.42214126],
       ...,
       [ 1.53208366, -0.30966177, -1.04868371, ...,  0.26630165,
         1.04100677, -0.42214126],
       [-0.65270587,  3.22932987, -1.04868371, ...,  0.52463793,
         4.55495365, -0.42214126],
       [-0.65270587, -0.30966177,  0.95357636, ...,  0.52463793,
        -0.71596668,  2.36887531]])

In [319]:
#Criando a rede
rede = Sequential()
#Camada de entrada
rede.add(Dense(units= 6, kernel_initializer='uniform', activation='relu', input_dim = 12))

rede.add(Dense(units= 6, kernel_initializer='uniform', activation='relu'))
#Camada de saída
rede.add(Dense(units= 1, kernel_initializer='uniform', activation='sigmoid'))

rede.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [320]:
#treinando a Rede
rede.fit(x_treino, y_treino, batch_size=10, epochs=100)

Epoch 1/100
80/80 [==============================] - 1s 1ms/step - loss: 0.6861 - accuracy: 0.6900
Epoch 2/100
80/80 [==============================] - 0s 1ms/step - loss: 0.6555 - accuracy: 0.6975
Epoch 3/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5937 - accuracy: 0.6975
Epoch 4/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5478 - accuracy: 0.6975
Epoch 5/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5322 - accuracy: 0.7163
Epoch 6/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5240 - accuracy: 0.7350
Epoch 7/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5194 - accuracy: 0.7400
Epoch 8/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5154 - accuracy: 0.7412
Epoch 9/100
80/80 [==============================] - 0s 1ms/step - loss: 0.5133 - accuracy: 0.7462
Epoch 10/100
80/80 [==============================] - 0s 999us/step - loss: 0.5113 - accuracy: 0.7425
Epoch 1

In [321]:
pred = rede.predict(x_teste)
pred = (pred > 0.5)
pred

7/7 [==============================] - 0s 1ms/step


array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [322]:
#Matriz de confusao
matriz = confusion_matrix(y_teste, pred)

In [323]:
matriz

array([[ 21,  37],
       [ 20, 122]])