<a href="https://colab.research.google.com/github/MariaNatiele/Redes_Neurais/blob/main/Redes_Neurais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Redes Neurais Artificiais(RNA) com a biblioteca Keras
</br>
[keras](https://keras.io/api/)

In [4]:
#Bibliotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

In [8]:
#importando a base de dados, x previsoes e y classe
dados = datasets.load_iris()
previsores = dados.data
classe = dados.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
#Transformando a classe em dammy -> cada valor vira uma coluna, teremos 3 neurônios de saída
classe_dammy = np_utils.to_categorical(classe)
#classe_dammy

In [11]:
#Separação de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, classe_dammy, random_state=0, test_size=0.3)

In [14]:
from keras.layers.serialization import activation
from keras.layers.core.dense import utils
#Criação da estrutura da rede neural com Sequential
rede = Sequential()
#Primeira camada, 5 neuronio e 4 neuronio de entrada, usamos input_dim = 4 pq tem 4 caracteristicas para prevê a classe
rede.add(Dense(units=5, input_dim = 4))
#Segunda camada oculta
rede.add(Dense(units=5))
#Terceira camada oculta
#função softmax pq a rede é de 3 camadas
rede.add(Dense(units=3, activation='softmax'))

In [15]:
#Visualizando um resumo da rede neural
rede.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 5)                 25        
                                                                 
 dense_4 (Dense)             (None, 5)                 30        
                                                                 
 dense_5 (Dense)             (None, 3)                 18        
                                                                 
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [18]:
#Configurando os paremetros da rede adam -> atualizar os pesos e loss -> erros

rede.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [19]:
#Treinando a rede neural
rede.fit(x_treino, y_treino, epochs=100, validation_data=(x_teste,y_teste))

Epoch 1/100
4/4 [==============================] - 2s 139ms/step - loss: 1.9950 - accuracy: 0.3714 - val_loss: 2.3165 - val_accuracy: 0.2444
Epoch 2/100
4/4 [==============================] - 0s 23ms/step - loss: 1.8479 - accuracy: 0.3714 - val_loss: 2.1369 - val_accuracy: 0.2444
Epoch 3/100
4/4 [==============================] - 0s 16ms/step - loss: 1.7259 - accuracy: 0.3714 - val_loss: 1.9619 - val_accuracy: 0.2444
Epoch 4/100
4/4 [==============================] - 0s 19ms/step - loss: 1.5982 - accuracy: 0.3714 - val_loss: 1.7951 - val_accuracy: 0.2444
Epoch 5/100
4/4 [==============================] - 0s 25ms/step - loss: 1.4796 - accuracy: 0.3714 - val_loss: 1.6358 - val_accuracy: 0.2444
Epoch 6/100
4/4 [==============================] - 0s 20ms/step - loss: 1.3719 - accuracy: 0.3714 - val_loss: 1.4888 - val_accuracy: 0.2444
Epoch 7/100
4/4 [==============================] - 0s 13ms/step - loss: 1.2682 - accuracy: 0.3714 - val_loss: 1.3593 - val_accuracy: 0.2444
Epoch 8/100
4/4 [==

In [20]:
#Previsão
previsao = rede.predict(x_teste)
previsao = (previsao > 0.5)
previsao

2/2 [==============================] - 0s 7ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [Fa

In [23]:
#
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(i) for i in previsao]

In [24]:
#Matriz de confusão
matriz = confusion_matrix(y_teste_matrix, y_previsao_matrix)
matriz

array([[16,  0,  0],
       [11,  1,  6],
       [ 0,  0, 11]])